# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: "#UCDPSS20"
title-normal: 2020 UC Davis Plant Science Symposium
email: 
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://plantsciencesymposium.ucdavis.edu" # the base hostname & protocol for your site
author: Gitanshu Munjal
street_address: UC Davis Conference Center
city: Davis
state: CA
zip_code: 95616
country: United States of America
phone: 

force-https: True

# Plugins
gems:
  - jekyll-sitemap
  - jemoji

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: 

# Build settings
markdown: kramdown

